import Kunai.Vocab

/-!
# Vocabulary data (generated)

Generated from `pkg/kunai/protocols/*.p4` by `go run ./spec/lean/gen/vocab2lean`.
Do not edit; regenerate with `make lean-vocab`.
-/
namespace Kunai

def vocab : Vocab :=
  { protos := [
      { name := "cw",
        fields := [⟨"first_nibble", 0, 4⟩, ⟨"flags", 4, 4⟩, ⟨"length", 8, 8⟩, ⟨"sequence", 16, 16⟩],
        fixedLen := 4 },
      { name := "esp",
        fields := [⟨"spi", 0, 32⟩, ⟨"seq", 32, 32⟩],
        fixedLen := 8 },
      { name := "eth",
        fields := [⟨"dst", 0, 48⟩, ⟨"src", 48, 48⟩, ⟨"ethertype", 96, 16⟩],
        fixedLen := 14 },
      { name := "geneve",
        fields := [⟨"version", 0, 2⟩, ⟨"opt_len", 2, 6⟩, ⟨"flags", 8, 8⟩, ⟨"protocol_type", 16, 16⟩, ⟨"vni", 32, 24⟩, ⟨"reserved", 56, 8⟩],
        fixedLen := 8,
        lenRule := some { byteOff := 0, mask := 63, shift := 0, scale := 4, base := 0, addend := 0 },
        requires := [("version", [0])],
        maxDepth := 4,
        machine := some {
          states := [
            { name := "start", extracts := [⟨"hdr", "geneve_h", 8, false⟩], counters := [.set "pc" { byteOff := 0, mask := 63, shift := 0, scale := 4, base := 0, addend := 0 }], advances := [], trans := .select { keys := [.field "hdr" false 0 2], cases := [⟨[.val 0], (.state 1)⟩], default := .reject } },
            { name := "walk", extracts := [], counters := [], advances := [], trans := .select { keys := [.counterIsZero "pc", .lookahead 24], cases := [⟨[.bool true, .wild], .accept⟩, ⟨[.bool false, .val 66176], (.state 2)⟩, ⟨[.bool false, .val 67587], (.state 3)⟩, ⟨[.bool false, .wild], .reject⟩], default := .reject } },
            { name := "parse_ovn", extracts := [⟨"ovn", "geneve_opt_ovn_h", 8, false⟩], counters := [.decLiteral "pc" 8], advances := [], trans := .goto (.state 1) },
            { name := "parse_gwlb", extracts := [⟨"gwlb", "geneve_opt_gwlb_h", 8, false⟩], counters := [.decLiteral "pc" 8], advances := [], trans := .goto (.state 1) }],
          entry := 0,
          headers := [⟨"geneve_opt_gwlb_h", [⟨"option_class", 0, 16⟩, ⟨"type", 16, 8⟩, ⟨"flags_len", 24, 8⟩, ⟨"flow_cookie", 32, 32⟩], 8⟩, ⟨"geneve_h", [⟨"version", 0, 2⟩, ⟨"opt_len", 2, 6⟩, ⟨"flags", 8, 8⟩, ⟨"protocol_type", 16, 16⟩, ⟨"vni", 32, 24⟩, ⟨"reserved", 56, 8⟩], 8⟩, ⟨"geneve_opt_ovn_h", [⟨"option_class", 0, 16⟩, ⟨"type", 16, 8⟩, ⟨"flags_len", 24, 8⟩, ⟨"rsv", 32, 1⟩, ⟨"ingress_port", 33, 15⟩, ⟨"egress_port", 48, 16⟩], 8⟩],
          options := [{ outParam := "gwlb", header := "geneve_opt_gwlb_h", kindByte := some 67587 }, { outParam := "ovn", header := "geneve_opt_ovn_h", kindByte := some 66176 }],
          stacks := [],
          tails := [],
          writebacks := [] },
        regionLoop := some 1,
        regionSkips := true },
      { name := "gre",
        fields := [⟨"flags", 0, 16⟩, ⟨"protocol_type", 16, 16⟩],
        fixedLen := 4,
        flagsByteOff := 0,
        flagTriggers := [⟨"c", 128, 4⟩, ⟨"k", 32, 4⟩, ⟨"s", 16, 4⟩] },
      { name := "gtp",
        fields := [⟨"version", 0, 3⟩, ⟨"pt", 3, 1⟩, ⟨"reserved", 4, 1⟩, ⟨"e", 5, 1⟩, ⟨"s", 6, 1⟩, ⟨"pn", 7, 1⟩, ⟨"msg_type", 8, 8⟩, ⟨"length", 16, 16⟩, ⟨"teid", 32, 32⟩],
        fixedLen := 8,
        maxDepth := 8,
        machine := some {
          states := [
            { name := "start", extracts := [⟨"gtp", "gtp_h", 8, false⟩], counters := [], advances := [], trans := .select { keys := [.field "gtp" false 5 1, .field "gtp" false 6 1, .field "gtp" false 7 1], cases := [⟨[.val 0, .val 0, .val 0], .accept⟩], default := (.state 1) } },
            { name := "parse_opt", extracts := [⟨"opt", "gtp_opt_h", 4, false⟩], counters := [], advances := [], trans := .select { keys := [.field "opt" false 24 8], cases := [⟨[.val 0], .accept⟩, ⟨[.wild], (.state 2)⟩], default := .reject } },
            { name := "parse_ext", extracts := [⟨"exts", "gtp_ext_h", 4, true⟩], counters := [], advances := [], trans := .select { keys := [.field "exts" true 24 8], cases := [⟨[.val 0], .accept⟩, ⟨[.wild], (.state 2)⟩], default := .reject } }],
          entry := 0,
          headers := [⟨"gtp_h", [⟨"version", 0, 3⟩, ⟨"pt", 3, 1⟩, ⟨"reserved", 4, 1⟩, ⟨"e", 5, 1⟩, ⟨"s", 6, 1⟩, ⟨"pn", 7, 1⟩, ⟨"msg_type", 8, 8⟩, ⟨"length", 16, 16⟩, ⟨"teid", 32, 32⟩], 8⟩, ⟨"gtp_ext_h", [⟨"ext_length", 0, 8⟩, ⟨"ext_type", 8, 16⟩, ⟨"next_ext", 24, 8⟩], 4⟩, ⟨"gtp_opt_h", [⟨"seq", 0, 16⟩, ⟨"npdu", 16, 8⟩, ⟨"next_ext", 24, 8⟩], 4⟩],
          options := [{ outParam := "opt", header := "gtp_opt_h", kindByte := none }],
          stacks := [{ name := "exts", header := "gtp_ext_h", capacity := 8, elemBytes := 4, ownerOption := "", offsetAfterOwner := 0 }],
          tails := [("gtp_ext_h", { byteOff := 0, mask := 255, shift := 0, scale := 4, base := 4, addend := 0 })],
          writebacks := [] } },
      { name := "icmp",
        fields := [⟨"type", 0, 8⟩, ⟨"code", 8, 8⟩, ⟨"checksum", 16, 16⟩],
        fixedLen := 4 },
      { name := "icmp6",
        fields := [⟨"type", 0, 8⟩, ⟨"code", 8, 8⟩, ⟨"checksum", 16, 16⟩],
        fixedLen := 4 },
      { name := "ipv4",
        fields := [⟨"version", 0, 4⟩, ⟨"ihl", 4, 4⟩, ⟨"diffserv", 8, 8⟩, ⟨"total_length", 16, 16⟩, ⟨"identification", 32, 16⟩, ⟨"flags", 48, 3⟩, ⟨"frag_offset", 51, 13⟩, ⟨"ttl", 64, 8⟩, ⟨"protocol", 72, 8⟩, ⟨"checksum", 80, 16⟩, ⟨"src", 96, 32⟩, ⟨"dst", 128, 32⟩],
        fixedLen := 20,
        lenRule := some { byteOff := 0, mask := 15, shift := 0, scale := 4, base := 20, addend := 0 },
        requires := [("version", [4])],
        machine := some {
          states := [
            { name := "start", extracts := [⟨"hdr", "ipv4_h", 20, false⟩], counters := [.set "pc" { byteOff := 0, mask := 15, shift := 0, scale := 4, base := 20, addend := 0 }], advances := [], trans := .select { keys := [.field "hdr" false 0 4], cases := [⟨[.val 4], (.state 1)⟩], default := .reject } },
            { name := "walk", extracts := [], counters := [], advances := [], trans := .select { keys := [.counterIsZero "pc", .lookahead 8], cases := [⟨[.bool true, .wild], .accept⟩, ⟨[.bool false, .val 0], .accept⟩, ⟨[.bool false, .val 1], (.state 2)⟩, ⟨[.bool false, .val 7], (.state 4)⟩, ⟨[.bool false, .val 148], (.state 3)⟩, ⟨[.bool false, .wild], .reject⟩], default := .reject } },
            { name := "parse_nop", extracts := [], counters := [.decLiteral "pc" 1], advances := [.literal 1], trans := .goto (.state 1) },
            { name := "parse_router_alert", extracts := [⟨"router_alert", "ipv4_opt_router_alert_h", 4, false⟩], counters := [.decLiteral "pc" 4], advances := [], trans := .goto (.state 1) },
            { name := "parse_rr", extracts := [], counters := [.decLookahead "pc" 1], advances := [.lookahead { byteOff := 1, mask := 255, shift := 0, scale := 1, base := 0, addend := 0 }], trans := .goto (.state 1) }],
          entry := 0,
          headers := [⟨"ipv4_h", [⟨"version", 0, 4⟩, ⟨"ihl", 4, 4⟩, ⟨"diffserv", 8, 8⟩, ⟨"total_length", 16, 16⟩, ⟨"identification", 32, 16⟩, ⟨"flags", 48, 3⟩, ⟨"frag_offset", 51, 13⟩, ⟨"ttl", 64, 8⟩, ⟨"protocol", 72, 8⟩, ⟨"checksum", 80, 16⟩, ⟨"src", 96, 32⟩, ⟨"dst", 128, 32⟩], 20⟩, ⟨"ipv4_rr_addr_h", [⟨"addr", 0, 32⟩], 4⟩, ⟨"ipv4_opt_router_alert_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩, ⟨"value", 16, 16⟩], 4⟩, ⟨"ipv4_opt_rr_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩, ⟨"pointer", 16, 8⟩], 3⟩],
          options := [{ outParam := "router_alert", header := "ipv4_opt_router_alert_h", kindByte := some 148 }, { outParam := "rr", header := "ipv4_opt_rr_h", kindByte := some 7 }],
          stacks := [{ name := "addrs", header := "ipv4_rr_addr_h", capacity := 9, elemBytes := 4, ownerOption := "rr", offsetAfterOwner := 3 }],
          tails := [],
          writebacks := [] },
        regionLoop := some 1,
        regionSkips := true },
      { name := "ipv6",
        fields := [⟨"version", 0, 4⟩, ⟨"traffic_class", 4, 8⟩, ⟨"flow_label", 12, 20⟩, ⟨"payload_length", 32, 16⟩, ⟨"next_header", 48, 8⟩, ⟨"hop_limit", 56, 8⟩, ⟨"src", 64, 128⟩, ⟨"dst", 192, 128⟩],
        fixedLen := 40,
        requires := [("version", [6])],
        maxDepth := 4,
        machine := some {
          states := [
            { name := "start", extracts := [⟨"hdr", "ipv6_h", 40, false⟩], counters := [], advances := [], trans := .select { keys := [.field "hdr" false 0 4, .field "hdr" false 48 8], cases := [⟨[.val 6, .val 0], (.state 1)⟩, ⟨[.val 6, .val 44], (.state 1)⟩, ⟨[.val 6, .val 60], (.state 1)⟩, ⟨[.val 6, .wild], .accept⟩], default := .reject } },
            { name := "parse_ext", extracts := [⟨"exts", "ipv6_ext_h", 8, true⟩], counters := [], advances := [], trans := .select { keys := [.field "exts" true 0 8], cases := [⟨[.val 0], (.state 1)⟩, ⟨[.val 44], (.state 1)⟩, ⟨[.val 60], (.state 1)⟩], default := .accept } }],
          entry := 0,
          headers := [⟨"ipv6_h", [⟨"version", 0, 4⟩, ⟨"traffic_class", 4, 8⟩, ⟨"flow_label", 12, 20⟩, ⟨"payload_length", 32, 16⟩, ⟨"next_header", 48, 8⟩, ⟨"hop_limit", 56, 8⟩, ⟨"src", 64, 128⟩, ⟨"dst", 192, 128⟩], 40⟩, ⟨"ipv6_ext_h", [⟨"next_header", 0, 8⟩, ⟨"hdr_ext_len", 8, 8⟩, ⟨"_opts", 16, 48⟩], 8⟩],
          options := [],
          stacks := [{ name := "exts", header := "ipv6_ext_h", capacity := 8, elemBytes := 8, ownerOption := "", offsetAfterOwner := 0 }],
          tails := [("ipv6_ext_h", { byteOff := 1, mask := 255, shift := 0, scale := 8, base := 0, addend := 0 })],
          writebacks := [("ipv6_ext_h", ⟨0, 6⟩)] } },
      { name := "mpls",
        fields := [⟨"label", 0, 20⟩, ⟨"tc", 20, 3⟩, ⟨"s", 23, 1⟩, ⟨"ttl", 24, 8⟩],
        fixedLen := 4,
        chainEnd := some ("s", 1),
        maxDepth := 8 },
      { name := "qinq",
        fields := [⟨"tci", 0, 16⟩, ⟨"ethertype", 16, 16⟩],
        fixedLen := 4 },
      { name := "srv6",
        fields := [⟨"next_header", 0, 8⟩, ⟨"hdr_ext_len", 8, 8⟩, ⟨"routing_type", 16, 8⟩, ⟨"segments_left", 24, 8⟩, ⟨"last_entry", 32, 8⟩, ⟨"flags", 40, 8⟩, ⟨"tag", 48, 16⟩],
        fixedLen := 8,
        requires := [("routing_type", [4])],
        machine := some {
          states := [
            { name := "start", extracts := [⟨"hdr", "srv6_h", 8, false⟩], counters := [.set "pc" { byteOff := 4, mask := 255, shift := 0, scale := 1, base := 0, addend := 1 }], advances := [], trans := .select { keys := [.field "hdr" false 16 8], cases := [⟨[.val 4], (.state 1)⟩], default := .reject } },
            { name := "walk", extracts := [], counters := [], advances := [], trans := .select { keys := [.counterIsZero "pc"], cases := [⟨[.bool true], .accept⟩, ⟨[.bool false], (.state 2)⟩], default := .reject } },
            { name := "consume_seg", extracts := [⟨"segments", "srv6_seg_h", 16, true⟩], counters := [.decLiteral "pc" 1], advances := [], trans := .goto (.state 1) }],
          entry := 0,
          headers := [⟨"srv6_h", [⟨"next_header", 0, 8⟩, ⟨"hdr_ext_len", 8, 8⟩, ⟨"routing_type", 16, 8⟩, ⟨"segments_left", 24, 8⟩, ⟨"last_entry", 32, 8⟩, ⟨"flags", 40, 8⟩, ⟨"tag", 48, 16⟩], 8⟩, ⟨"srv6_seg_h", [⟨"addr", 0, 128⟩], 16⟩],
          options := [],
          stacks := [{ name := "segments", header := "srv6_seg_h", capacity := 8, elemBytes := 16, ownerOption := "", offsetAfterOwner := 0 }],
          tails := [],
          writebacks := [] },
        regionLoop := some 1 },
      { name := "tcp",
        fields := [⟨"sport", 0, 16⟩, ⟨"dport", 16, 16⟩, ⟨"seq", 32, 32⟩, ⟨"ack", 64, 32⟩, ⟨"data_offset", 96, 4⟩, ⟨"reserved", 100, 3⟩, ⟨"flags", 103, 9⟩, ⟨"window", 112, 16⟩, ⟨"checksum", 128, 16⟩, ⟨"urgent_ptr", 144, 16⟩],
        fixedLen := 20,
        lenRule := some { byteOff := 12, mask := 240, shift := 4, scale := 4, base := 20, addend := 0 },
        maxDepth := 40,
        machine := some {
          states := [
            { name := "start", extracts := [⟨"hdr", "tcp_h", 20, false⟩], counters := [.set "pc" { byteOff := 12, mask := 240, shift := 4, scale := 4, base := 20, addend := 0 }], advances := [], trans := .select { keys := [.field "hdr" false 96 4], cases := [⟨[.val 5], .accept⟩], default := (.state 1) } },
            { name := "parse_options", extracts := [], counters := [], advances := [], trans := .select { keys := [.counterIsZero "pc", .lookahead 8], cases := [⟨[.bool true, .wild], .accept⟩, ⟨[.bool false, .val 0], .accept⟩, ⟨[.bool false, .val 1], (.state 2)⟩, ⟨[.bool false, .val 2], (.state 3)⟩, ⟨[.bool false, .val 3], (.state 4)⟩, ⟨[.bool false, .val 4], (.state 5)⟩, ⟨[.bool false, .val 5], (.state 7)⟩, ⟨[.bool false, .val 8], (.state 6)⟩, ⟨[.bool false, .wild], (.state 8)⟩], default := .reject } },
            { name := "parse_nop", extracts := [], counters := [.decLiteral "pc" 1], advances := [.literal 1], trans := .goto (.state 1) },
            { name := "parse_mss", extracts := [⟨"mss", "tcp_opt_mss_h", 4, false⟩], counters := [.decLiteral "pc" 4], advances := [], trans := .select { keys := [.field "mss" false 8 8], cases := [⟨[.val 4], (.state 1)⟩], default := .reject } },
            { name := "parse_ws", extracts := [⟨"ws", "tcp_opt_ws_h", 3, false⟩], counters := [.decLiteral "pc" 3], advances := [], trans := .select { keys := [.field "ws" false 8 8], cases := [⟨[.val 3], (.state 1)⟩], default := .reject } },
            { name := "parse_sack_perm", extracts := [⟨"sack_perm", "tcp_opt_sack_perm_h", 2, false⟩], counters := [.decLiteral "pc" 2], advances := [], trans := .select { keys := [.field "sack_perm" false 8 8], cases := [⟨[.val 2], (.state 1)⟩], default := .reject } },
            { name := "parse_ts", extracts := [⟨"ts", "tcp_opt_ts_h", 10, false⟩], counters := [.decLiteral "pc" 10], advances := [], trans := .select { keys := [.field "ts" false 8 8], cases := [⟨[.val 10], (.state 1)⟩], default := .reject } },
            { name := "parse_sack", extracts := [], counters := [.decLookahead "pc" 1], advances := [.lookahead { byteOff := 1, mask := 255, shift := 0, scale := 1, base := 0, addend := 0 }], trans := .goto (.state 1) },
            { name := "parse_unknown_opt", extracts := [], counters := [.decLookahead "pc" 1], advances := [.lookahead { byteOff := 1, mask := 255, shift := 0, scale := 1, base := 0, addend := 0 }], trans := .goto (.state 1) }],
          entry := 0,
          headers := [⟨"tcp_h", [⟨"sport", 0, 16⟩, ⟨"dport", 16, 16⟩, ⟨"seq", 32, 32⟩, ⟨"ack", 64, 32⟩, ⟨"data_offset", 96, 4⟩, ⟨"reserved", 100, 3⟩, ⟨"flags", 103, 9⟩, ⟨"window", 112, 16⟩, ⟨"checksum", 128, 16⟩, ⟨"urgent_ptr", 144, 16⟩], 20⟩, ⟨"tcp_opt_mss_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩, ⟨"value", 16, 16⟩], 4⟩, ⟨"tcp_opt_sack_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩], 2⟩, ⟨"tcp_opt_sack_perm_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩], 2⟩, ⟨"tcp_sack_block_h", [⟨"left", 0, 32⟩, ⟨"right", 32, 32⟩], 8⟩, ⟨"tcp_opt_ts_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩, ⟨"tsval", 16, 32⟩, ⟨"tsecr", 48, 32⟩], 10⟩, ⟨"tcp_opt_ws_h", [⟨"kind", 0, 8⟩, ⟨"length", 8, 8⟩, ⟨"shift", 16, 8⟩], 3⟩],
          options := [{ outParam := "mss", header := "tcp_opt_mss_h", kindByte := some 2 }, { outParam := "sack", header := "tcp_opt_sack_h", kindByte := some 5 }, { outParam := "sack_perm", header := "tcp_opt_sack_perm_h", kindByte := some 4 }, { outParam := "ts", header := "tcp_opt_ts_h", kindByte := some 8 }, { outParam := "ws", header := "tcp_opt_ws_h", kindByte := some 3 }],
          stacks := [{ name := "blocks", header := "tcp_sack_block_h", capacity := 4, elemBytes := 8, ownerOption := "sack", offsetAfterOwner := 2 }],
          tails := [],
          writebacks := [] },
        regionLoop := some 1,
        regionSkips := true },
      { name := "udp",
        fields := [⟨"sport", 0, 16⟩, ⟨"dport", 16, 16⟩, ⟨"length", 32, 16⟩, ⟨"checksum", 48, 16⟩],
        fixedLen := 8 },
      { name := "vlan",
        fields := [⟨"tci", 0, 16⟩, ⟨"ethertype", 16, 16⟩],
        fixedLen := 4 },
      { name := "vxlan",
        fields := [⟨"flags", 0, 8⟩, ⟨"reserved1", 8, 24⟩, ⟨"vni", 32, 24⟩, ⟨"reserved2", 56, 8⟩],
        fixedLen := 8 }
]
    edges := [
      ⟨"cw", "mpls", .noCheck⟩,
      ⟨"esp", "ipv4", .field "protocol" [50]⟩,
      ⟨"esp", "ipv6", .field "next_header" [50]⟩,
      ⟨"eth", "mpls", .noCheck⟩,
      ⟨"eth", "cw", .noCheck⟩,
      ⟨"eth", "vxlan", .noCheck⟩,
      ⟨"eth", "geneve", .noCheck⟩,
      ⟨"geneve", "udp", .field "dport" [6081]⟩,
      ⟨"gre", "ipv4", .field "protocol" [47]⟩,
      ⟨"gre", "ipv6", .field "next_header" [47]⟩,
      ⟨"gtp", "udp", .field "dport" [2152]⟩,
      ⟨"icmp", "ipv4", .field "protocol" [1]⟩,
      ⟨"icmp6", "ipv6", .field "next_header" [58]⟩,
      ⟨"ipv4", "eth", .field "ethertype" [2048]⟩,
      ⟨"ipv4", "vlan", .field "ethertype" [2048]⟩,
      ⟨"ipv4", "qinq", .field "ethertype" [2048]⟩,
      ⟨"ipv4", "srv6", .field "next_header" [4]⟩,
      ⟨"ipv4", "ipv4", .field "protocol" [4]⟩,
      ⟨"ipv4", "gre", .field "protocol_type" [2048]⟩,
      ⟨"ipv6", "eth", .field "ethertype" [34525]⟩,
      ⟨"ipv6", "vlan", .field "ethertype" [34525]⟩,
      ⟨"ipv6", "qinq", .field "ethertype" [34525]⟩,
      ⟨"ipv6", "gre", .field "protocol_type" [34525]⟩,
      ⟨"ipv6", "ipv6", .field "next_header" [41]⟩,
      ⟨"mpls", "eth", .field "ethertype" [34887]⟩,
      ⟨"mpls", "vlan", .field "ethertype" [34887]⟩,
      ⟨"mpls", "qinq", .field "ethertype" [34887]⟩,
      ⟨"mpls", "mpls", .noCheck⟩,
      ⟨"qinq", "eth", .field "ethertype" [34984]⟩,
      ⟨"srv6", "ipv6", .field "next_header" [43]⟩,
      ⟨"tcp", "ipv4", .field "protocol" [6]⟩,
      ⟨"tcp", "ipv6", .field "next_header" [6]⟩,
      ⟨"tcp", "srv6", .field "next_header" [6]⟩,
      ⟨"udp", "ipv4", .field "protocol" [17]⟩,
      ⟨"udp", "ipv6", .field "next_header" [17]⟩,
      ⟨"udp", "srv6", .field "next_header" [17]⟩,
      ⟨"vlan", "eth", .field "ethertype" [33024]⟩,
      ⟨"vlan", "qinq", .field "ethertype" [33024]⟩,
      ⟨"vlan", "vlan", .field "ethertype" [33024]⟩,
      ⟨"vxlan", "udp", .field "dport" [4789, 8472]⟩
] }

end Kunai
